import { addDays, toISODate } from "@/lib/date";

import type { Appointment } from "@/lib/types";

function isoDateOffset(days: number): string {
  return toISODate(addDays(new Date(), days));
}

export const MOCK_APPOINTMENTS: Appointment[] = [
  {
    id: "1",
    client: "Samarco Mineração",
    description: "Análise de vibração em motores e redutores da linha de beneficiamento",
    serviceType: "Análise de Vibração",
    date: isoDateOffset(0),
    time: "08:00",
    assignee: "Rafael Mendes",
    status: "in-progress",
    address: "Unidade Industrial - Anchieta/ES",
    notes: "Priorizar os ativos críticos da linha 03.",
    createdAt: new Date().toISOString(),
  },
  {
    id: "2",
    client: "ArcelorMittal Brasil",
    description: "Coleta de amostras e avaliação da condição do óleo de redutores",
    serviceType: "Análise de Óleo",
    date: isoDateOffset(0),
    time: "10:30",
    assignee: "Camila Rodrigues",
    status: "scheduled",
    address: "Planta Industrial - Serra/ES",
    createdAt: new Date().toISOString(),
  },
  {
    id: "3",
    client: "Suzano Papel e Celulose",
    description: "Inspeção termográfica em painéis elétricos e equipamentos rotativos",
    serviceType: "Termografia",
    date: isoDateOffset(1),
    time: "14:00",
    assignee: "André Oliveira",
    status: "scheduled",
    address: "Unidade Industrial - Aracruz/ES",
    createdAt: new Date().toISOString(),
  },
  {
    id: "4",
    client: "Vale S.A.",
    description: "Implantação de plano de gestão da lubrificação para ativos críticos",
    serviceType: "Gestão da Lubrificação",
    date: isoDateOffset(1),
    time: "08:30",
    assignee: "Marcos Ferreira",
    status: "scheduled",
    address: "Complexo Industrial - Vitória/ES",
    notes: "Mapear pontos críticos e revisar periodicidades.",
    createdAt: new Date().toISOString(),
  },
  {
    id: "5",
    client: "Petrobras",
    description: "Inspeção ultrassônica para identificação de vazamentos em sistemas industriais",
    serviceType: "Ultrassom",
    date: isoDateOffset(-1),
    time: "09:00",
    assignee: "Camila Rodrigues",
    status: "done",
    address: "Unidade Operacional - São José dos Campos/SP",
    createdAt: new Date().toISOString(),
  },
  {
    id: "6",
    client: "Braskem",
    description: "Filtragem e purificação do óleo hidráulico de equipamentos críticos",
    serviceType: "Filtragem de Óleo",
    date: isoDateOffset(-2),
    time: "13:30",
    assignee: "Rafael Mendes",
    status: "done",
    address: "Complexo Petroquímico - Camaçari/BA",
    createdAt: new Date().toISOString(),
  },
  {
    id: "13",
    client: "Vale S.A.",
    description: "Inspeção termográfica de motores, painéis e equipamentos industriais",
    serviceType: "Termografia",
    date: isoDateOffset(3),
    time: "14:00",
    assignee: "André Oliveira",
    status: "scheduled",
    address: "Complexo Industrial - Vitória/ES",
    notes: "Inspeção preventiva antes da parada programada.",
    createdAt: new Date().toISOString(),
  },
  {
    id: "14",
    client: "ArcelorMittal Brasil",
    description: "Revisão do plano de lubrificação dos equipamentos da linha de laminação",
    serviceType: "Gestão da Lubrificação",
    date: isoDateOffset(4),
    time: "08:30",
    assignee: "Marcos Ferreira",
    status: "scheduled",
    address: "Planta Industrial - Serra/ES",
    notes: "Revisar periodicidade e pontos de aplicação.",
    createdAt: new Date().toISOString(),
  },
  {
    id: "15",
    client: "Braskem",
    description: "Identificação de vazamentos em linhas e equipamentos utilizando ultrassom",
    serviceType: "Ultrassom",
    date: isoDateOffset(4),
    time: "11:00",
    assignee: "Camila Rodrigues",
    status: "scheduled",
    address: "Complexo Petroquímico - Camaçari/BA",
    createdAt: new Date().toISOString(),
  },
  {
    id: "16",
    client: "CSN - Companhia Siderúrgica Nacional",
    description: "Balanceamento dinâmico de conjunto rotativo do sistema de bombeamento",
    serviceType: "Alinhamento e Balanceamento",
    date: isoDateOffset(-2),
    time: "14:30",
    assignee: "André Oliveira",
    status: "scheduled",
    address: "Unidade Industrial - Volta Redonda/RJ",
    notes: "Confirmar parada do equipamento antes da chegada da equipe.",
    createdAt: new Date().toISOString(),
  },
  {
    id: "18",
    client: "Usiminas",
    description: "Instalação de sistema de lubrificação automática em mancais",
    serviceType: "Lubrificação Automática",
    date: isoDateOffset(5),
    time: "09:30",
    assignee: "Marcos Ferreira",
    status: "scheduled",
    address: "Planta Industrial - Ipatinga/MG",
    notes: "Material de instalação já separado no almoxarifado.",
    createdAt: new Date().toISOString(),
  },
  {
    id: "21",
    client: "Votorantim Cimentos",
    description: "Análise de vibração em ventiladores e motores do processo produtivo",
    serviceType: "Análise de Vibração",
    date: isoDateOffset(6),
    time: "08:30",
    assignee: "André Oliveira",
    status: "scheduled",
    address: "Unidade Industrial - Sobradinho/DF",
    createdAt: new Date().toISOString(),
  },
  {
    id: "25",
    client: "WEG",
    description: "Inspeção ultrassônica em componentes e sistemas pneumáticos",
    serviceType: "Ultrassom",
    date: isoDateOffset(7),
    time: "10:00",
    assignee: "Camila Rodrigues",
    status: "scheduled",
    address: "Unidade Industrial - Jaraguá do Sul/SC",
    createdAt: new Date().toISOString(),
  },
  {
    id: "26",
    client: "Suzano Papel e Celulose",
    description: "Alinhamento a laser de conjunto motor-bomba",
    serviceType: "Alinhamento e Balanceamento",
    date: isoDateOffset(7),
    time: "14:00",
    assignee: "André Oliveira",
    status: "scheduled",
    address: "Unidade Industrial - Mucuri/BA",
    notes: "Equipamento deverá permanecer parado durante a execução.",
    createdAt: new Date().toISOString(),
  },
];

export const SERVICE_TYPES = [
  "Análise de Vibração",
  "Análise de Óleo",
  "Termografia",
  "Gestão da Lubrificação",
  "Ultrassom",
  "Filtragem de Óleo",
  "Alinhamento e Balanceamento",
  "Lubrificação Automática",
  "Monitoramento de Condição",
  "Auditoria de Lubrificação",
];

export const ASSIGNEES = [
  "Rafael Mendes",
  "Camila Rodrigues",
  "André Oliveira",
  "Marcos Ferreira",
];